The previous section contains an example of an inline hint in an XML file.  Below is the Windup decorator that led to the inline hint.  The `windup:xpath-value` decorator is used to pinpoint a location within an XML file to target for an inline hint.  The `windup:regex-hint` then adds the hint to the XML element point-pointed using the XPath expression.

[source,xml]
------------------
<windup:xpath-value description="Weblogic Specific"
        xpath="//*[@value='org.hibernate.transaction.WeblogicTransactionManagerLookup']/@value | //property[@name='transaction.manager_lookup_class' and .='org.hibernate.transaction.WeblogicTransactionManagerLookup']/text()"
        effort="1" inline="true">
    <windup:hints>
        <windup:regex-hint regex="org.hibernate.transaction.WeblogicTransactionManagerLookup$" 
                hint="Replace with: org.hibernate.transaction.JBossTransactionManagerLookup"/>
    </windup:hints>
</windup:xpath-value>
------------------
    
In the example above, Windup applies the decorator `windup:xpath-value` to the XML file, and looks for an element with the `value` attribute `org.hibernate.transaction.WeblogicTransactionManagerLookup`.  When this is matched, Windup adds the description "Weblogic Specific" to the Windup resource report, and highlights the line.

Next, Windup processes all `windup:hints`.  In this case, the `windup:regex-hint` applies against the value extracted in the `windup:xpath-value` decorator.  The inline hint "Replace with: org.hibernate.transaction.JBossTransactionManagerLookup" is included with the highlighted line.

6.4.1 The XPath element
~~~~~~~~~~~~~~~~~~~~~~~

Attributes on the XPath element include:

description (string)::
  the description of the match
xpath (xpath)::
  the xpath to match against
effort (int)::
  number of story points to implement estimated changes
inline (int)::
  whether to include the match inline or at the top of the file as a highlight

6.4.1.1 XPath Namespaces
^^^^^^^^^^^^^^^^^^^^^^^^

[NOTE]
The `windup:namespace` tag can be used to provide one or more namespace prefix to uri mappings. All namespace prefixes in the xpath expression must have a cooresponding `windup:namespace` tag.

Nested elements on the XPath Value include:

* `windup:namespace`
* `windup:hints`
* `windup:decorators`

6.4.2 Regex Hint
~~~~~~~~~~~~~~~~

Attributes on the Regex Hint include:

hint (string)::
  the inline hint to define the Java if the Regex matches
effort (int)::
  number of story points to implement estimated changes
regex (regex)::
  regular expression to match against

